
import { Profile } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    name: 'Ananya Iyer',
    age: 26,
    height: "5'4\"",
    religion: 'Hindu',
    caste: 'Brahmin',
    location: 'Adyar, Chennai',
    district: 'Chennai',
    taluk: 'Mylapore',
    pincode: '600020',
    education: 'M.Tech Computer Science',
    occupation: 'Software Engineer',
    image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&q=80&w=400',
    gender: 'Female',
    about: 'I am a simple, down-to-earth person with a mix of traditional and modern values.',
    email: 'ananya@example.com',
    password: 'password123'
  },
  {
    id: '2',
    name: 'Karthik Raja',
    age: 29,
    height: "5'11\"",
    religion: 'Hindu',
    caste: 'Vanniyar',
    location: 'Peelamedu, Coimbatore',
    district: 'Coimbatore',
    taluk: 'Coimbatore North',
    pincode: '641004',
    education: 'MBA Finance',
    occupation: 'Project Manager',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    gender: 'Male',
    about: 'Ambitious professional who loves traveling and exploring new cultures.',
    email: 'karthik@example.com',
    password: 'password123'
  },
  {
    id: '3',
    name: 'Priyanka Nair',
    age: 25,
    height: "5'5\"",
    religion: 'Hindu',
    caste: 'Nair',
    location: 'Anna Nagar, Madurai',
    district: 'Madurai',
    taluk: 'Madurai North',
    pincode: '625020',
    education: 'MBBS',
    occupation: 'Doctor',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    gender: 'Female',
    about: 'Dedicated healthcare professional seeking someone who understands the demands of a medical career.',
    email: 'priyanka@example.com',
    password: 'password123'
  },
  {
    id: '4',
    name: 'Siddharth Menon',
    age: 31,
    height: "6'0\"",
    religion: 'Hindu',
    caste: 'Menon',
    location: 'Thillai Nagar, Trichy',
    district: 'Tiruchirappalli',
    taluk: 'Trichy West',
    pincode: '620018',
    education: 'B.E. Mechanical',
    occupation: 'Business Owner',
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    gender: 'Male',
    about: 'I run a manufacturing business and enjoy weekend cycling trips.',
    email: 'siddharth@example.com',
    password: 'password123'
  },
  {
    id: '5',
    name: 'Deepika Raman',
    age: 27,
    height: "5'3\"",
    religion: 'Hindu',
    caste: 'Pillai',
    location: 'Fairlands, Salem',
    district: 'Salem',
    taluk: 'Salem South',
    pincode: '636016',
    education: 'MA English Literature',
    occupation: 'Content Strategist',
    image: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=400',
    gender: 'Female',
    about: 'Voracious reader and a fan of Carnatic music. Looking for a soulful companion.',
    email: 'deepika@example.com',
    password: 'password123'
  },
  {
    id: '6',
    name: 'Arjun Vijay',
    age: 30,
    height: "5'10\"",
    religion: 'Christian',
    caste: 'Protestant',
    location: 'Palayamkottai, Tirunelveli',
    district: 'Tirunelveli',
    taluk: 'Palayamkottai',
    pincode: '627002',
    education: 'MS Data Science',
    occupation: 'Data Scientist',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    gender: 'Male',
    about: 'Tech enthusiast who loves dogs and long drives. Balanced personality.',
    email: 'arjun@example.com',
    password: 'password123'
  }
];
